#yml格式  xx:空格 值

#端口号修改
server: 
  port: 80

spring: 
# 邮箱配置 
  mail: 
#邮箱服务器地址
    host: smtp.qq.com 
    username: 1023998784@qq.com
 # 密码为邮箱授权码
    password: tuakugafmxrlbffb
    properties: 
     mail: 
      smtp: 
       auth: true  
       starttls: 
        enable: true  
        required: true
#spring mysql配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/mobilemall
    username: root
    password: a
  thymeleaf: 
  #    prefix: classpath:/templates/
  #    suffix: .html
    cache: false #关闭缓存
#  mvc: 
#    static-path-pattern: /static/**
  messages: 
    basename: i18n.login,i18n.top
     #指定国际化配置文件路径+基础名



