package yc.MobileMall.bean;

public class Boughtgoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boughtgoods.id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boughtgoods.goods_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boughtgoods.goods_num
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private Integer goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boughtgoods.user_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boughtgoods.receiver_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boughtgoods.reviews_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private Integer reviewsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boughtgoods.id
     *
     * @return the value of boughtgoods.id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boughtgoods.id
     *
     * @param id the value for boughtgoods.id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boughtgoods.goods_id
     *
     * @return the value of boughtgoods.goods_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boughtgoods.goods_id
     *
     * @param goodsId the value for boughtgoods.goods_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boughtgoods.goods_num
     *
     * @return the value of boughtgoods.goods_num
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boughtgoods.goods_num
     *
     * @param goodsNum the value for boughtgoods.goods_num
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boughtgoods.user_id
     *
     * @return the value of boughtgoods.user_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boughtgoods.user_id
     *
     * @param userId the value for boughtgoods.user_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boughtgoods.receiver_id
     *
     * @return the value of boughtgoods.receiver_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boughtgoods.receiver_id
     *
     * @param receiverId the value for boughtgoods.receiver_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boughtgoods.reviews_id
     *
     * @return the value of boughtgoods.reviews_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public Integer getReviewsId() {
        return reviewsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boughtgoods.reviews_id
     *
     * @param reviewsId the value for boughtgoods.reviews_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setReviewsId(Integer reviewsId) {
        this.reviewsId = reviewsId;
    }
}