package yc.MobileMall.bean;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.goods_class
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private String goodsClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.goods_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.goods_class
     *
     * @return the value of class.goods_class
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public String getGoodsClass() {
        return goodsClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.goods_class
     *
     * @param goodsClass the value for class.goods_class
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setGoodsClass(String goodsClass) {
        this.goodsClass = goodsClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.goods_id
     *
     * @return the value of class.goods_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.goods_id
     *
     * @param goodsId the value for class.goods_id
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}