package yc.MobileMall.bean;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.dis_price
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer disPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brands
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String brands;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.product_code
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.weight
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.reward_points
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer rewardPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.availability
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer availability;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goosdes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String goosdes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.class_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.reviews
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer reviews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.salesnum_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer salesnumId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.dis_price
     *
     * @return the value of goods.dis_price
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getDisPrice() {
        return disPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.dis_price
     *
     * @param disPrice the value for goods.dis_price
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setDisPrice(Integer disPrice) {
        this.disPrice = disPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brands
     *
     * @return the value of goods.brands
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getBrands() {
        return brands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brands
     *
     * @param brands the value for goods.brands
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setBrands(String brands) {
        this.brands = brands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.product_code
     *
     * @return the value of goods.product_code
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.product_code
     *
     * @param productCode the value for goods.product_code
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.weight
     *
     * @return the value of goods.weight
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.weight
     *
     * @param weight the value for goods.weight
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.reward_points
     *
     * @return the value of goods.reward_points
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getRewardPoints() {
        return rewardPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.reward_points
     *
     * @param rewardPoints the value for goods.reward_points
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setRewardPoints(Integer rewardPoints) {
        this.rewardPoints = rewardPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.availability
     *
     * @return the value of goods.availability
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getAvailability() {
        return availability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.availability
     *
     * @param availability the value for goods.availability
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setAvailability(Integer availability) {
        this.availability = availability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goosdes
     *
     * @return the value of goods.goosdes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getGoosdes() {
        return goosdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goosdes
     *
     * @param goosdes the value for goods.goosdes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setGoosdes(String goosdes) {
        this.goosdes = goosdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.class_id
     *
     * @return the value of goods.class_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.class_id
     *
     * @param classId the value for goods.class_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.reviews
     *
     * @return the value of goods.reviews
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getReviews() {
        return reviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.reviews
     *
     * @param reviews the value for goods.reviews
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setReviews(Integer reviews) {
        this.reviews = reviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.salesnum_id
     *
     * @return the value of goods.salesnum_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getSalesnumId() {
        return salesnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.salesnum_id
     *
     * @param salesnumId the value for goods.salesnum_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setSalesnumId(Integer salesnumId) {
        this.salesnumId = salesnumId;
    }
}