package yc.MobileMall.bean;

public class Imgs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.id
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.src
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    private String src;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.goods_id
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.id
     *
     * @return the value of imgs.id
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.id
     *
     * @param id the value for imgs.id
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.src
     *
     * @return the value of imgs.src
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.src
     *
     * @param src the value for imgs.src
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    public void setSrc(String src) {
        this.src = src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.goods_id
     *
     * @return the value of imgs.goods_id
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.goods_id
     *
     * @param goodsId the value for imgs.goods_id
     *
     * @mbg.generated Wed May 15 21:50:59 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}