package yc.MobileMall.bean;

public class Receiver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.first_name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.last_name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.company
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.country
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.province
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.city
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.address
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.email
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.zipCode
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.telephone
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.fax
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.order_notes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private String orderNotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiver.user_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.id
     *
     * @return the value of receiver.id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.id
     *
     * @param id the value for receiver.id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.first_name
     *
     * @return the value of receiver.first_name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.first_name
     *
     * @param firstName the value for receiver.first_name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.last_name
     *
     * @return the value of receiver.last_name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.last_name
     *
     * @param lastName the value for receiver.last_name
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.company
     *
     * @return the value of receiver.company
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.company
     *
     * @param company the value for receiver.company
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.country
     *
     * @return the value of receiver.country
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.country
     *
     * @param country the value for receiver.country
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.province
     *
     * @return the value of receiver.province
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.province
     *
     * @param province the value for receiver.province
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.city
     *
     * @return the value of receiver.city
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.city
     *
     * @param city the value for receiver.city
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.address
     *
     * @return the value of receiver.address
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.address
     *
     * @param address the value for receiver.address
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.email
     *
     * @return the value of receiver.email
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.email
     *
     * @param email the value for receiver.email
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.zipCode
     *
     * @return the value of receiver.zipCode
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.zipCode
     *
     * @param zipcode the value for receiver.zipCode
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setZipcode(Integer zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.telephone
     *
     * @return the value of receiver.telephone
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.telephone
     *
     * @param telephone the value for receiver.telephone
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.fax
     *
     * @return the value of receiver.fax
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.fax
     *
     * @param fax the value for receiver.fax
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.order_notes
     *
     * @return the value of receiver.order_notes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public String getOrderNotes() {
        return orderNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.order_notes
     *
     * @param orderNotes the value for receiver.order_notes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setOrderNotes(String orderNotes) {
        this.orderNotes = orderNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receiver.user_id
     *
     * @return the value of receiver.user_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receiver.user_id
     *
     * @param userId the value for receiver.user_id
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

	@Override
	public String toString() {
		return "Receiver [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", company=" + company
				+ ", country=" + country + ", province=" + province + ", city=" + city + ", address=" + address
				+ ", email=" + email + ", zipcode=" + zipcode + ", telephone=" + telephone + ", fax=" + fax
				+ ", orderNotes=" + orderNotes + ", userId=" + userId + "]";
	}
    
    
}