package yc.MobileMall.bean;

public class Sizes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sizes.id
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sizes.size
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sizes.goods_id
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sizes.id
     *
     * @return the value of sizes.id
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sizes.id
     *
     * @param id the value for sizes.id
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sizes.size
     *
     * @return the value of sizes.size
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sizes.size
     *
     * @param size the value for sizes.size
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sizes.goods_id
     *
     * @return the value of sizes.goods_id
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sizes.goods_id
     *
     * @param goodsId the value for sizes.goods_id
     *
     * @mbg.generated Tue Apr 30 19:28:52 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}