package yc.MobileMall.bean;

import java.util.Date;

public class Transaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.goods_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.user_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.receiver_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.totalprice
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    private Integer totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transdate
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    private Date transdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.estimatedtime
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    private Date estimatedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.id
     *
     * @return the value of transaction.id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.id
     *
     * @param id the value for transaction.id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.goods_id
     *
     * @return the value of transaction.goods_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.goods_id
     *
     * @param goodsId the value for transaction.goods_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.user_id
     *
     * @return the value of transaction.user_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.user_id
     *
     * @param userId the value for transaction.user_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.receiver_id
     *
     * @return the value of transaction.receiver_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.receiver_id
     *
     * @param receiverId the value for transaction.receiver_id
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.totalprice
     *
     * @return the value of transaction.totalprice
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public Integer getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.totalprice
     *
     * @param totalprice the value for transaction.totalprice
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public void setTotalprice(Integer totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transdate
     *
     * @return the value of transaction.transdate
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transdate
     *
     * @param transdate the value for transaction.transdate
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.estimatedtime
     *
     * @return the value of transaction.estimatedtime
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public Date getEstimatedtime() {
        return estimatedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.estimatedtime
     *
     * @param estimatedtime the value for transaction.estimatedtime
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    public void setEstimatedtime(Date estimatedtime) {
        this.estimatedtime = estimatedtime;
    }
}