package yc.MobileMall.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yc.MobileMall.bean.Receiver;
import yc.MobileMall.bean.ReceiverExample;

public interface ReceiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    long countByExample(ReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int deleteByExample(ReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int insert(Receiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int insertSelective(Receiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    List<Receiver> selectByExample(ReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    Receiver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Receiver record, @Param("example") ReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByExample(@Param("record") Receiver record, @Param("example") ReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByPrimaryKeySelective(Receiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receiver
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByPrimaryKey(Receiver record);
}