package yc.MobileMall.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yc.MobileMall.bean.Reviews;
import yc.MobileMall.bean.ReviewsExample;

public interface ReviewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    long countByExample(ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    int deleteByExample(ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    int insert(Reviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    int insertSelective(Reviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    List<Reviews> selectByExample(ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    Reviews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Reviews record, @Param("example") ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    int updateByExample(@Param("record") Reviews record, @Param("example") ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    int updateByPrimaryKeySelective(Reviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated Wed May 08 20:46:56 CST 2019
     */
    int updateByPrimaryKey(Reviews record);
}