package yc.MobileMall.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yc.MobileMall.bean.Salesnum;
import yc.MobileMall.bean.SalesnumExample;

public interface SalesnumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    long countByExample(SalesnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int deleteByExample(SalesnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int insert(Salesnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int insertSelective(Salesnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    List<Salesnum> selectByExample(SalesnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    Salesnum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Salesnum record, @Param("example") SalesnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByExample(@Param("record") Salesnum record, @Param("example") SalesnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByPrimaryKeySelective(Salesnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesnum
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByPrimaryKey(Salesnum record);
}