package yc.MobileMall.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yc.MobileMall.bean.Shopcart;
import yc.MobileMall.bean.ShopcartExample;

public interface ShopcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    long countByExample(ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    int deleteByExample(ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    int insert(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    int insertSelective(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    List<Shopcart> selectByExample(ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    Shopcart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Shopcart record, @Param("example") ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    int updateByExample(@Param("record") Shopcart record, @Param("example") ShopcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    int updateByPrimaryKeySelective(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbg.generated Sun May 19 10:39:54 CST 2019
     */
    int updateByPrimaryKey(Shopcart record);
}