package yc.MobileMall.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yc.MobileMall.bean.Sizes;
import yc.MobileMall.bean.SizesExample;

public interface SizesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    long countByExample(SizesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int deleteByExample(SizesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int insert(Sizes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int insertSelective(Sizes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    List<Sizes> selectByExample(SizesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    Sizes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Sizes record, @Param("example") SizesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByExample(@Param("record") Sizes record, @Param("example") SizesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByPrimaryKeySelective(Sizes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sizes
     *
     * @mbg.generated Thu May 09 20:53:02 CST 2019
     */
    int updateByPrimaryKey(Sizes record);
}